DROP TABLE IF EXISTS PAYMENT_METHOD;
CREATE TABLE PAYMENT_METHOD(ID INT PRIMARY KEY, NAME VARCHAR(255), DISPLAY_NAME VARCHAR(255), PAYMENT_TYPE VARCHAR(255));
create sequence payment_method_seq;
INSERT INTO PAYMENT_METHOD VALUES(1, 'credit card', 'credit card', 'CREDIT_CARD');
INSERT INTO PAYMENT_METHOD VALUES(2, 'debit card', 'debit card', 'DEBIT_CARD');



DROP TABLE IF EXISTS PAYMENT_PLAN;
CREATE TABLE PAYMENT_PLAN(ID INT PRIMARY KEY, NET_AMOUNT NUMERIC(10, 2), TAX_AMOUNT NUMERIC(10, 2), GROSS_AMOUNT NUMERIC(10, 2), CURRENCY VARCHAR(10), DURATION VARCHAR(10), PAYMENT_METHOD_ID INT);

ALTER TABLE PAYMENT_PLAN 
    ADD FOREIGN KEY (PAYMENT_METHOD_ID) 
    REFERENCES PAYMENT_METHOD(ID);
create sequence payment_plan_seq;
INSERT INTO PAYMENT_PLAN VALUES(1, 5.99, 0, 5.99,'USD', 'MONTH', 1);


